############################################################
@local = https://localhost:6999
@deploy = https://

############################################################
### 
POST {{local}}/getAuthCode
content-type: application/json

{
    "formId": "CA4BD51AE638F911E8A68ED8C462D60FE6B1432C11311E21DEE4CC2595D81BA8"
}
### 
POST {{local}}/sendForm
content-type: application/json

{
    "authCode": "fe194d145e4ba8a5d88605f89dab2b1ae2474697ec64a1b0053efe7118560e6f",
    "formData": {
        "title": "FormTITLE",
        "message": "FormMESSAGE"
    }
}



############################################################
### deployment requests
POST {{deploy}}/route
content-type: application/json

{
}