############################################################
@local = https://localhost:6999
@deploy = https://

############################################################
### 
POST {{local}}/getAuthCode
content-type: application/json

{
    "formId": "CA4BD51AE638F911E8A68ED8C462D60FE6B1432C11311E21DEE4CC2595D81BA8"
}
### 
POST {{local}}/sendForm
content-type: application/json

{
    "authCode": "f7574e93ef7a97ff769329197fa05ea51f91ed1df5a8697149eb158218d42f07",
    "formData": {
        "name": "Mr Nami Namer",
        "email": "master@lennymail.at",
        "company": "DotV OÜ",
        "company-address": "Narva mnt  7",
        "zip-code": "666",
        "country": "Estonia",
        "message": "Hallo Ihr Leute, ich sage heute, ich fresse eure Häute, auf dass ich super schweinefresser bedeute. Ihr seid meine Beute"
    }
}



############################################################
### deployment requests
POST {{deploy}}/route
content-type: application/json

{
}